// Generated by CoffeeScript 1.7.1
(function() {
  var FetchKaHandler;

  exports.FetchKaHandler = FetchKaHandler = (function() {
    var InnerBuilder;

    InnerBuilder = (function() {
      function InnerBuilder() {
        this.params = {};
        this.params.topic = "*";
        this.params.name = (function() {
          var id, _results;
          id = "";
          _results = [];
          while (id.length < 8) {
            _results.push(id += Math.random().toString(36).substr(2));
          }
          return _results;
        })();
        this.params.onMessage = function() {
          return null;
        };
        this.params.onError = function() {
          return null;
        };
      }

      InnerBuilder.prototype.setName = function(name) {
        this.params.name = name;
        return this;
      };

      InnerBuilder.prototype.setTopic = function(topic) {
        this.params.topic = topic;
        return this;
      };

      InnerBuilder.prototype.setOnMessage = function(onMessage) {
        this.params.onMessage = onMessage;
        return this;
      };

      InnerBuilder.prototype.setOnError = function(onError) {
        this.params.onError = onError;
        return this;
      };

      InnerBuilder.prototype.set = function(options) {
        var key, value;
        for (key in options) {
          value = options[key];
          this.params[key] = value;
        }
        this.counter = 0;
        return this;
      };

      InnerBuilder.prototype.build = function() {
        return new FetchKaHandler(this.params);
      };

      return InnerBuilder;

    })();

    FetchKaHandler.Builder = function() {
      return new InnerBuilder;
    };

    function FetchKaHandler(options) {
      var key, value;
      for (key in options) {
        value = options[key];
        this[key] = value;
      }
    }

    return FetchKaHandler;

  })();

}).call(this);
