// Generated by CoffeeScript 1.7.1
(function() {
  var FetchKaConsumer, FetchKaHandler, consumer, fetchka, handler, onMessage;

  fetchka = require("../fetchka");

  FetchKaConsumer = fetchka.FetchKaConsumer;

  FetchKaHandler = fetchka.FetchKaHandler;

  onMessage = function(message) {
    return console.log("builder", message);
  };

  handler = new FetchKaHandler.Builder().setTopic("orders").setOnMessage(onMessage).build();

  consumer = new FetchKaConsumer.Builder().addTopic("orders").connectString("localhost:2181").build();

  consumer.register(new FetchKaHandler.Builder().setTopic("orders").setOnMessage(onMessage).build()).register(new FetchKaHandler.Builder().set({
    topic: "orders",
    onMessage: (function(data) {
      return console.log("hash", data);
    }),
    onError: (function(err) {
      return console.log(err);
    })
  }).build()).start();

}).call(this);
