// Generated by CoffeeScript 1.7.1
(function() {
  var FetchKaProducer, producer;

  FetchKaProducer = require("../fetchka").FetchKaProducer;

  producer = new FetchKaProducer.Builder().connectString("localhost:2181").setTopics(["orders"]).build();

  producer.ready(function() {
    producer.sendOne("orders", "test", function(err, data) {
      return console.log(err, data);
    });
    return producer.send([
      {
        topic: "orders",
        messages: {
          message: "test"
        },
        partition: 0
      }
    ], function(err, data) {
      return console.log(err, data);
    });
  });

}).call(this);
