// Generated by CoffeeScript 1.7.1
(function() {
  var FetchKaProducer, producer;

  FetchKaProducer = require("../fetchka").FetchKaProducer;

  producer = new FetchKaProducer.Builder().connectString("localhost:2181").setTopics(["orders"]).build();

  producer.ready(function() {
    var i, _i, _results;
    _results = [];
    for (i = _i = 1; _i <= 10; i = ++_i) {
      _results.push(producer.sendOne("orders", {
        customer: {
          email: "test@test.com"
        }
      }, function(err, data) {
        return console.log(err, data);
      }));
    }
    return _results;
  });

}).call(this);
