// Generated by CoffeeScript 1.7.1
(function() {
  var FetchKaProducer, producer;

  FetchKaProducer = require("../fetchKa/fetchka").FetchKaProducer;

  producer = new FetchKaProducer.Builder().connectString("localhost:2181/kafka0.8").setTopics(["orders"]).build();

  producer.ready(function() {
    return producer.send([
      {
        topic: "orders",
        messages: "test",
        partition: 0
      }
    ], function(err, data) {
      return console.log(err, data);
    });
  });

}).call(this);
