// Generated by CoffeeScript 1.7.1
(function() {
  var fetchka;

  fetchka = require("./fetchka/fetchka");

  exports.FetchKaConsumer = fetchka.FetchKaConsumer;

  exports.FetchKaProducer = fetchka.FetchKaProducer;

  exports.FetchKaHandler = fetchka.FetchKaHandler;

}).call(this);
