// Generated by CoffeeScript 1.7.1
(function() {
  var fetchka, fetchkatree;

  fetchka = require("./fetchka/fetchka");

  fetchkatree = require("./fetchka/routing");

  exports.FetchKaConsumer = fetchka.FetchKaConsumer;

  exports.FetchKaProducer = fetchka.FetchKaProducer;

  exports.FetchKaHandler = fetchka.FetchKaHandler;

  exports.FetchKaTree = fetchkatree.FetchKaTree;

  exports.FetchKaRouting = fetchkatree.FetchKaRouting;

}).call(this);
